In [ ]:
class student():
    def __init__(self,name,age):
        self.name=name
        self.age=age
    def __str__(self):
        # magic function
        return f"name is {self.name} and age is {self.age}"
    
    def __repr__(self):
        return f"name is {self.name} and age is {self.age}"

        

In [16]:
s1=student("nada",21)
s1

name is nada and age is 21

In [17]:
import numpy as np

In [18]:
x=[1,2,3,4]
v=np.array(x)
v

array([1, 2, 3, 4])

In [21]:
s = np.array(5)
print(s.ndim)
print(s.shape)
print(s)
print("========")
 
v = np.array([1,2,3,4,5,6])
print(v.ndim)
print(v.shape)
print(v)
print("========")

m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(m.ndim)
print(m.shape)
print(m)

0
()
5
1
(6,)
[1 2 3 4 5 6]
2
(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
vec=np.array([1,2,3,4,5,6])
mat =vec.reshape((3,2))
print(mat)
print(mat.shape[1])

[[1 2]
 [3 4]
 [5 6]]
2


In [25]:
vec=np.array([1,2,3,4,5,6])
mat =vec.reshape(vec.shape[0],1)
print(mat)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [28]:
vec=np.array([1,2,3,4])
vec[:, None]

array([[1],
       [2],
       [3],
       [4]])

In [29]:
def array_reshape(arr:list,rows:int=-1,cols:int=-1):
    try:
        arr=np.array(arr)
        return arr.reshape(rows,cols)
    except (TypeError,ValueError) as e:
        raise ValueError(f"Invalid reshape operation: {e}")

In [11]:
vec=[1,2,3,4,5,6]
array_reshape(vec,2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
mat =np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(mat.dtype)

mat =np.array([[1,2,3],
              [4,5.5,6],
              [7,8,9]])
print(mat.dtype)

mat =np.array([[1,2,3],
              [True,5,6],
              [7,8,9]])
print(mat.dtype)

mat =np.array([[1,2,'3'],
              [4,5.5,6],
              [7,8,9]])
print(mat.dtype)
print(mat)

int64
float64
int64
<U32
[['1' '2' '3']
 ['4' '5.5' '6']
 ['7' '8' '9']]


In [37]:
mat =np.array([[1,2,'3'],
              [4,5.5,6],
              [7,8,9]])

fmat =m.astype(float)
print(fmat)
print(fmat.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64


In [43]:
mat =np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
v = np.array([3,2,5,1])
print(m[1,2])
print("---------")
print( m[1:3,0:2])
print("---------")
print(m[-3:-1,-3:-1])
print("---------")



6
---------
[[4 5]
 [7 8]]
---------
[[1 2]
 [4 5]]
---------


In [45]:
mat =np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

matT=mat.T
matT

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
mat =np.zeros((3,4))
print(mat)
print("---------")
mat =np.ones((3,4))
print(mat)
print("---------")
mat =np.full((3,4),5)
print(mat)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
---------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
---------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
